### ISSUE TITLE
Log is not registering the stop time

### ISSUE THREAD

**Issue by mbartz** [LPgenerator/django-mmc#12]
In __mmc_store_log(), the script calls MMCLog.logging().  If there is an instance of the log already, logging() calls an update on the model instance.  The attribute "end" is auto_now and is NOT updated.

I think the logging() method has to recognize the difference between and update and create and manually assign the current datetime to the "end" attribute.

**Comment by gotlium** [comment]
PR?

**Comment by mbartz** [comment]
Add a patch branch with a proposed change.  I have tested locally on 1.9.5.

**Comment by gotlium** [comment]
Thanks. Fixed version is available on PyPi.
