### ISSUE TITLE
PyPi Tarball Is Not In Sync With Master

### ISSUE THREAD

**Issue by dtstbnow** [LPgenerator/django-mmc#20]
Currently PyPi's copy of django-mmc is missing some changes present here, the differences I've noticed are in defaults.py and mixins.py.  Defaults.py is missing the NOTIFICATION_LIMIT and NEW_SCRIPT_NOTIFICATION variables, and mixins.py does not reference them.

**Comment by gotlium** [comment]
Hi, all releases are available at https://github.com/LPgenerator/django-mmc/releases. Master under development with new features.

**Comment by dtstbnow** [comment]
Thanks for the help.
